In [ ]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Mounted at /gdrive
/gdrive


In [ ]:
cd /content/drive/MyDrive/123/powerful-gnns

/content/drive/MyDrive/123/powerful-gnns


In [ ]:
!python3 main.py --dataset combineqg23 --filename modelqg23,2 --batch_size 64  --num_layers 8    

loading data
# classes: 2
# maximum node tag: 23
# data: 21000
/usr/local/lib/python3.7/dist-packages/torch/optim/lr_scheduler.py:134: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
epoch: 1: 100% 50/50 [00:03<00:00, 13.43batch/s]
loss training: 4.979987
accuracy train: 0.786614 test: 0.776667, loss test: 1.344530, loss train: 1.225854

Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0.], requires_grad=True)
epoch: 2: 100% 50/50 [00:03<00:00, 13.79batch/s]
loss training: 1.854256
accuracy train: 0.822116 test: 0.817619, loss test: 1.064715, loss train: 0.9

In [ ]:
!python3 main.py --dataset combineqg23 --filename modelqg23,9 --epoch 450  --num_layers 8

loading data
# classes: 2
# maximum node tag: 23
# data: 21000
/usr/local/lib/python3.7/dist-packages/torch/optim/lr_scheduler.py:134: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
epoch: 1: 100% 50/50 [00:01<00:00, 25.87batch/s]
loss training: 6.644084
accuracy train: 0.774392 test: 0.773333, loss test: 5.293581, loss train: 5.321900

Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0.], requires_grad=True)
epoch: 2: 100% 50/50 [00:01<00:00, 25.95batch/s]
loss training: 4.260931
accuracy train: 0.725873 test: 0.735714, loss test: 6.563806, loss train: 6.2

In [ ]:
!python3 main.py --dataset combinehg2 --filename modelhg2,7 --epoch 400 --final_dropout 0  --num_layers 8 --batch_size 128

loading data
# classes: 2
# maximum node tag: 1
# data: 21000
/usr/local/lib/python3.7/dist-packages/torch/optim/lr_scheduler.py:134: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
epoch: 1: 100% 50/50 [00:42<00:00,  1.16batch/s]
loss training: 11.225349
accuracy train: 0.764974 test: 0.763333, loss test: 3.808864, loss train: 3.380201

Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0.], requires_grad=True)
epoch: 2: 100% 50/50 [00:43<00:00,  1.14batch/s]
loss training: 2.760441
accuracy train: 0.500159 test: 0.500000, loss test: 16.173521, loss train: 15

In [ ]:
!python3 main.py --dataset combinehg2 --filename modelhg2,10 --epoch 400  --num_layers 8 --batch_size 128

In [ ]:
!python3 main.py --dataset combinehg2 --filename modelhg2,6 --epoch 400 --batch_size 64

loading data
# classes: 2
# maximum node tag: 1
# data: 21000
/usr/local/lib/python3.7/dist-packages/torch/optim/lr_scheduler.py:134: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
epoch: 1: 100% 50/50 [00:19<00:00,  2.60batch/s]
loss training: 12.818731
accuracy train: 0.753651 test: 0.750476, loss test: 3.066505, loss train: 2.970973

Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0.], requires_grad=True)
epoch: 2: 100% 50/50 [00:18<00:00,  2.65batch/s]
loss training: 3.510374
accuracy train: 0.703810 test: 0.691905, loss test: 3.143945, loss train: 2.9